---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kong-jwt-secrets.serviceAccountName" . }}-role
rules:
- apiGroups:
  - ""
  resourceNames:
  - kong-jwt-secrets
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
{{- end }}

---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kong-jwt-secrets.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kong-jwt-secrets.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kong-jwt-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}