## @section Global parameters
## Global Docker image parameters
## @param global.imageRegistry Global Docker image registry
global:
  imageRegistry: ""

# Default values for kong-jwt-secrets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: sunbird
  repository: kong-jwt-secrets
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
restartPolicy: "OnFailure"

annotations:
  helm.sh/hook: post-install, post-upgrade, post-delete

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: true

rbac:
  create: false

consumersToBePresentInSecrets: 
 - echo-user
# - api-admin
