# Default values for kong-jwt-secrets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: keshavprasad/kong-jwt-secrets
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
restartPolicy: "OnFailure"

annotations:
  helm.sh/hook: post-install, post-upgrade, post-delete

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: true

rbac:
  create: true

consumersToBePresentInSecrets: 
 - echo-user
 #- api-admin
